// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzHjutu-ICbuqby4NruOgI43I3SGrfeIM',
    appId: '1:938925885472:web:1356427f17b34d4cb91445',
    messagingSenderId: '938925885472',
    projectId: 'four-hours-5d3dd',
    authDomain: 'four-hours-5d3dd.firebaseapp.com',
    storageBucket: 'four-hours-5d3dd.appspot.com',
    measurementId: 'G-K894QQ41HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3A4gw5Tbcu6pG-EKzu6G2J0vRqauFeU',
    appId: '1:938925885472:android:0cb2e4b9e8fa5179b91445',
    messagingSenderId: '938925885472',
    projectId: 'four-hours-5d3dd',
    storageBucket: 'four-hours-5d3dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2464wuKAYS817T9Gi2iF3HXipqr7IXFs',
    appId: '1:938925885472:ios:5f7cb7d3e91c4768b91445',
    messagingSenderId: '938925885472',
    projectId: 'four-hours-5d3dd',
    storageBucket: 'four-hours-5d3dd.appspot.com',
    iosClientId: '938925885472-986lg85l4e7afn2sgo36q99ecshepa6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fourHoursClient',
  );
}
